language: node_js
node_js:
  - '16'
  - '18'
before_install:
  - npm install -g coveralls
after_success:
  - coveralls < ./coverage/lcov.info
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+(-.*)?$/
